export const CATEGORIES = ['All', 'Arcade', 'Strategy', 'Puzzle', 'Racing', 'Sports', 'Multiplayer'];

export const GAMES = [
  {
    id: 'tic-tac-toe',
    title: 'Tic Tac Toe',
    description: 'Classic 3×3 strategy. Outsmart the AI or challenge a friend.',
    category: 'Strategy',
    players: { min: 1, max: 2 },
    icon: '⭕',
    color: '#ffffff',
    difficulty: 'Easy',
    featured: true,
    tags: ['classic', 'strategy', 'AI'],
  },
  {
    id: 'connect-four',
    title: 'Connect Four',
    description: 'Drop discs, connect 4 in a row. Gravity-defying strategy.',
    category: 'Strategy',
    players: { min: 1, max: 2 },
    icon: '🔴',
    color: '#ffffff',
    difficulty: 'Medium',
    featured: true,
    tags: ['classic', 'strategy', 'AI'],
  },
  {
    id: 'snake',
    title: 'Snake',
    description: 'Eat, grow, survive. Multiplayer snake chaos on one keyboard.',
    category: 'Arcade',
    players: { min: 1, max: 3 },
    icon: '🐍',
    color: '#ffffff',
    difficulty: 'Medium',
    featured: true,
    tags: ['arcade', 'multiplayer', 'AI'],
  },
  {
    id: 'pong',
    title: 'Pong',
    description: 'The original arcade classic. 1v1 paddle battle.',
    category: 'Sports',
    players: { min: 1, max: 2 },
    icon: '🏓',
    color: '#ffffff',
    difficulty: 'Easy',
    featured: false,
    tags: ['arcade', 'sports', 'AI'],
  },
  {
    id: 'breakout',
    title: 'Breakout',
    description: 'Smash bricks with powerups. Beat the high score.',
    category: 'Arcade',
    players: { min: 1, max: 1 },
    icon: '🧱',
    color: '#ffffff',
    difficulty: 'Medium',
    featured: true,
    tags: ['arcade', 'highscore', 'powerups'],
  },
  {
    id: 'memory-match',
    title: 'Memory Match',
    description: 'Flip cards, match pairs. Test your memory against the clock.',
    category: 'Puzzle',
    players: { min: 1, max: 2 },
    icon: '🃏',
    color: '#ffffff',
    difficulty: 'Easy',
    featured: false,
    tags: ['puzzle', 'memory', 'multiplayer'],
  },
  {
    id: 'rock-paper-scissors',
    title: 'RPS Arena',
    description: 'Rock, paper, scissors with animated battles and best-of-5.',
    category: 'Strategy',
    players: { min: 1, max: 2 },
    icon: '✊',
    color: '#ffffff',
    difficulty: 'Easy',
    featured: false,
    tags: ['strategy', 'multiplayer', 'AI'],
  },
  {
    id: 'maze-runner',
    title: 'Maze Runner',
    description: 'Navigate procedurally generated mazes. Race AI opponents.',
    category: 'Puzzle',
    players: { min: 1, max: 2 },
    icon: '🌀',
    color: '#ffffff',
    difficulty: 'Medium',
    featured: false,
    tags: ['puzzle', 'maze', 'AI'],
  },
  {
    id: 'racing-arena',
    title: 'Racing Arena',
    description: 'Top-down racing. Outrun AI cars on procedural tracks.',
    category: 'Racing',
    players: { min: 1, max: 2 },
    icon: '🏎️',
    color: '#ffffff',
    difficulty: 'Medium',
    featured: true,
    tags: ['racing', 'multiplayer', 'AI'],
  },
  {
    id: 'tank-battle',
    title: 'Tank Battle',
    description: 'Armored combat. Shoot, dodge, and destroy AI tanks.',
    category: 'Arcade',
    players: { min: 1, max: 2 },
    icon: '🪖',
    color: '#ffffff',
    difficulty: 'Hard',
    featured: true,
    tags: ['arcade', 'shooting', 'AI'],
  },
  {
    id: 'space-shooter',
    title: 'Space Shooter',
    description: 'Vertical shooter with enemy waves and boss fights.',
    category: 'Arcade',
    players: { min: 1, max: 1 },
    icon: '🚀',
    color: '#ffffff',
    difficulty: 'Hard',
    featured: true,
    tags: ['arcade', 'shooter', 'boss'],
  },
  {
    id: 'bomber-arena',
    title: 'Bomber Arena',
    description: 'Bomberman-style arena. Place bombs, chain explosions, survive.',
    category: 'Multiplayer',
    players: { min: 1, max: 3 },
    icon: '💣',
    color: '#ffffff',
    difficulty: 'Hard',
    featured: true,
    tags: ['multiplayer', 'strategy', 'AI'],
  },
];

export const getGame = (id) => GAMES.find(g => g.id === id) || null;
export const getByCategory = (cat) => cat === 'All' ? GAMES : GAMES.filter(g => g.category === cat);
export const getFeatured = () => GAMES.filter(g => g.featured);
